#output "compute_network_names" {
#  value = module.dynamic_deployment.compute_network_names
#}

#output "autogenerated_compute_routers_0" {
#  value = module.dynamic_deployment.autogenerated_compute_routers_0
#}

output "autogenerated_compute_routers" {
  value = module.dynamic_deployment.autogenerated_compute_routers
}
