output "compute_network_names" {
  value = local.compute_network_names
}

#output "autogenerated_compute_routers_0" {
#  value = local.autogenerated_compute_routers_0
#}

output "autogenerated_compute_routers" {
  value = local.autogenerated_compute_routers
}

output "compute_networks_1" {
  value = local.compute_networks_1
}

